### ISSUE TITLE
Howto install this plugin

### ISSUE THREAD

**Issue by loewal** [jrghnng/owrxantswitcher#1]
As the title says...
Would be very useful for testing!!

**Comment by jrghnng** [comment]
The plugin is installed as layed out in https://groups.io/g/openwebrx/message/9485.

In my case I put  the .js and .css file in /usr/lib/python3/dist-packages/htdocs/plugins/receiver/owrxantswitcher on the OpenWebRX server and added  

Plugins.load('owrxantswitcher');

to the init.js file in /usr/lib/python3/dist-packages/htdocs/plugins/receiver

To get a working solution, you also need a WebAPI running on the OpenWebRX server. In my case it is a .NET application listening on port 5001 for the commands sent by the Plugin. 

The WebAPI server needs to fit your setup, e.g. needs to trigger the actual switch which is somehow connected to the OpenWebRX server.

In my case I use a Coaxial Relay that is contnrolled by an Arduino Nano. The WebAPI sends commads via the serial connection to the Arduino and receives the status of the switch in return, which in turn is sent back to the Plugin on the client side. The Plugin updates the "highlighted" status of the antenna buttons.

Does this answer your question?
